name: open_items
description: The flutter client for open-items.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.3
  nanoid: ^1.0.0
  flutter_slidable: ^3.0.0
  cupertino_icons: ^1.0.2
  package_info_plus: ^4.0.2
  path_provider: ^2.0.11
  file_picker: ^5.3.2
  tuple: ^2.0.0
  intl: ^0.18.1
  permission_handler: ^11.0.0
  riverpod_annotation: ^2.2.0
  url_strategy: ^0.2.0
  flutter_native_splash: ^2.3.3
  flutter_markdown: ^0.6.18
  shared_preferences: ^2.2.2
  fpdart: ^1.1.0
  google_fonts: ^6.1.0
  collection: ^1.17.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0 # `flutter packages pub run build_runner build`
  build_runner: ^2.1.7
  flutter_lints: ^2.0.2
  riverpod_generator: ^2.3.3
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_app_name:
    git:
      url: https://github.com/doonfrs/flutter_app_name
      ref: f2febf1fd8de673292e7d18f4cc14ae90003dec3

flutter:
  uses-material-design: true

  assets:
    - "assets/icons/launcher/open_items.png"
    - "assets/icons/splash/open_items.png"
    - "assets/icons/splash/open_items_android_12.png"

  fonts:
    # ~/.pub-cache/bin/generator ./icons OpenItemsIcons.otf -o OpenItemsIcons.dart -v --no-normalize
    - family: OpenItemsIcons
      fonts:
        - asset: "assets/icons/custom/OpenItemsIcons.otf"

# dart run flutter_app_name
flutter_app_name:
  name: "Open-Items"
  id: "org.open_items"

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher/open_items.png"
  web:
    generate: true
    image_path: "assets/icons/launcher/open_items.png"
    background_color: "#000000"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/launcher/open_items.png"
    icon_size: 128

# dart run flutter_native_splash:create
# Remove (dart run flutter_native_splash:remove)
flutter_native_splash:
  color: "#000000"
  image: assets/icons/splash/open_items.png
  android_12:
    image: assets/icons/splash/open_items_android_12.png
    icon_background_color: "#000000"
